# Stage 1: Build the Deno application
FROM denoland/deno:alpine AS builder

# Set the working directory to /app
WORKDIR /app

# Copy the Deno program to the container
COPY watchdog /app/watchdog

# cache the dependencies
RUN deno cache /app/watchdog/main.ts

# run the watchdog
CMD ["deno", "run", "--allow-net", "--allow-read", "--allow-env", "--allow-write", "/app/watchdog/main.ts"]
